[package]
name = "brc20v2"
version = "0.1.0"
edition = "2024"
license = "CC0-1.0"

[dependencies]
hex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sha2 = "0.10.8"
thiserror = "2.0.11"
web3 = { version = "0.19.0", default-features = false, features = ["http", "tokio"] }
