[package]
name = "brc20v2"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10.8"
web3 = "0.19.0"
