[package]
name = "brc20v2"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

authors.workspace = true

description = "BRC-20 v2 cross-chain relay utilities"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
hex = "0.4.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
sha2 = "0.10.8"
web3 = { version = "0.19.0", features = ["http", "signing"] }
